--// insert into references 4 country
-- Migration SQL that makes the change goes here.
INSERT INTO references VALUES (401,'Country','AE','United Arab Emirates','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (402,'Country','AE','阿拉伯联合酋长国','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (403,'Country','AL','Albania','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (404,'Country','AL','阿尔巴尼亚','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (405,'Country','AR','Argentina','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (406,'Country','AR','阿根廷','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (407,'Country','AT','Austria','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (408,'Country','AT','奥地利','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (409,'Country','AU','Australia','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (410,'Country','AU','澳大利亚','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (411,'Country','BE','Belgium','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (412,'Country','BE','比利时','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (413,'Country','BG','Bulgaria','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (414,'Country','BG','保加利亚','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (415,'Country','BH','Bahrain','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (416,'Country','BH','巴林','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (417,'Country','BO','Bolivia','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (418,'Country','BO','玻利维亚','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (419,'Country','BR','Brazil','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (420,'Country','BR','巴西','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (421,'Country','BY','Belarus','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (422,'Country','BY','白俄罗斯','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (423,'Country','CA','Canada','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (424,'Country','CA','加拿大','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (425,'Country','CH','Switzerland','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (426,'Country','CH','瑞士','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (427,'Country','CL','Chile','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (428,'Country','CL','智利','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (429,'Country','CN','China','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (430,'Country','CN','中国','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (431,'Country','CO','Colombia','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (432,'Country','CO','哥伦比亚','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (433,'Country','CR','Costa Rica','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (434,'Country','CR','哥斯达黎加','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (435,'Country','CZ','Czech Republic','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (436,'Country','CZ','捷克共和国','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (437,'Country','DE','Germany','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (438,'Country','DE','德国','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (439,'Country','DK','Denmark','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (440,'Country','DK','丹麦','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (441,'Country','DO','Dominican Republic','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (442,'Country','DO','多米尼加共和国','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (443,'Country','DZ','Algeria','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (444,'Country','DZ','阿尔及利亚','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (445,'Country','EC','Ecuador','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (446,'Country','EC','厄瓜多尔','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (447,'Country','EE','Estonia','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (448,'Country','EE','爱沙尼亚','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (449,'Country','EG','Egypt','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (450,'Country','EG','埃及','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (451,'Country','ES','Spain','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (452,'Country','ES','西班牙','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (453,'Country','FI','Finland','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (454,'Country','FI','芬兰','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (455,'Country','FR','France','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (456,'Country','FR','法国','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (457,'Country','GB','United Kingdom','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (458,'Country','GB','英国','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (459,'Country','GR','Greece','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (460,'Country','GR','希腊','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (461,'Country','GT','Guatemala','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (462,'Country','GT','危地马拉','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (463,'Country','HK','Hong Kong','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (464,'Country','HK','香港','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (465,'Country','HN','Honduras','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (466,'Country','HN','洪都拉斯','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (467,'Country','HR','Croatia','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (468,'Country','HR','克罗地亚','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (469,'Country','HU','Hungary','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (470,'Country','HU','匈牙利','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (471,'Country','IE','Ireland','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (472,'Country','IE','爱尔兰','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (473,'Country','IL','Israel','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (474,'Country','IL','以色列','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (475,'Country','IN','India','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (476,'Country','IN','印度','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (477,'Country','IQ','Iraq','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (478,'Country','IQ','伊拉克','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (479,'Country','IS','Iceland','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (480,'Country','IS','冰岛','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (481,'Country','IT','Italy','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (482,'Country','IT','意大利','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (483,'Country','JO','Jordan','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (484,'Country','JO','约旦','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (485,'Country','JP','Japan','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (486,'Country','JP','日本','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (487,'Country','KR','South Korea','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (488,'Country','KR','南朝鲜','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (489,'Country','KW','Kuwait','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (490,'Country','KW','科威特','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (491,'Country','LB','Lebanon','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (492,'Country','LB','黎巴嫩','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (493,'Country','LT','Lithuania','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (494,'Country','LT','立陶宛','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (495,'Country','LU','Luxembourg','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (496,'Country','LU','卢森堡','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (497,'Country','LV','Latvia','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (498,'Country','LV','拉脱维亚','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (499,'Country','LY','Libya','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (500,'Country','LY','利比亚','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (501,'Country','MA','Morocco','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (502,'Country','MA','摩洛哥','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (503,'Country','MK','Macedonia','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (504,'Country','MK','马其顿王国','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (505,'Country','MX','Mexico','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (506,'Country','MX','墨西哥','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (507,'Country','NI','Nicaragua','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (508,'Country','NI','尼加拉瓜','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (509,'Country','NL','Netherlands','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (510,'Country','NL','荷兰','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (511,'Country','NO','Norway','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (512,'Country','NO','挪威','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (513,'Country','NZ','New Zealand','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (514,'Country','NZ','新西兰','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (515,'Country','OM','Oman','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (516,'Country','OM','阿曼','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (517,'Country','PA','Panama','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (518,'Country','PA','巴拿马','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (519,'Country','PE','Peru','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (520,'Country','PE','秘鲁','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (521,'Country','PL','Poland','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (522,'Country','PL','波兰','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (523,'Country','PR','Puerto Rico','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (524,'Country','PR','波多黎哥','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (525,'Country','PT','Portugal','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (526,'Country','PT','葡萄牙','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (527,'Country','PY','Paraguay','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (528,'Country','PY','巴拉圭','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (529,'Country','QA','Qatar','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (530,'Country','QA','卡塔尔','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (531,'Country','RO','Romania','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (532,'Country','RO','罗马尼亚','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (533,'Country','RU','Russia','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (534,'Country','RU','俄罗斯','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (535,'Country','SA','Saudi Arabia','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (536,'Country','SA','沙特阿拉伯','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (537,'Country','SD','Sudan','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (538,'Country','SD','苏丹','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (539,'Country','SE','Sweden','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (540,'Country','SE','瑞典','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (541,'Country','SI','Slovenia','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (542,'Country','SI','斯洛文尼亚','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (543,'Country','SK','Slovakia','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (544,'Country','SK','斯洛伐克','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (545,'Country','SV','El Salvador','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (546,'Country','SV','萨尔瓦多','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (547,'Country','SY','Syria','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (548,'Country','SY','叙利亚','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (549,'Country','TH','Thailand','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (550,'Country','TH','泰国','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (551,'Country','TN','Tunisia','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (552,'Country','TN','突尼斯','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (553,'Country','TR','Turkey','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (554,'Country','TR','土耳其','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (555,'Country','TW','Taiwan','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (556,'Country','TW','台湾地区','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (557,'Country','UA','Ukraine','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (558,'Country','UA','乌克兰','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (559,'Country','US','United States','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (560,'Country','US','美国','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (561,'Country','UY','Uruguay','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (562,'Country','UY','乌拉圭','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (563,'Country','VE','Venezuela','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (564,'Country','VE','委内瑞拉','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (565,'Country','VN','Vietnam','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (566,'Country','VN','越南','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (567,'Country','YE','Yemen','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (568,'Country','YE','也门','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (569,'Country','ZA','South Africa','en','','createdBy',SYSDATE,'createdBy',SYSDATE);
INSERT INTO references VALUES (570,'Country','ZA','南非','zh','','createdBy',SYSDATE,'createdBy',SYSDATE);


--//@UNDO
-- SQL to undo the change goes here.
DELETE FROM references WHERE ID >= 401 AND ID <=570; 

