package com.bulain.hibernate.entity;
// Generated 2011-10-25 20:06:48 by Hibernate Tools 3.2.2.GA



/**
 * Bike generated by hbm2java
 */
public class Bike extends com.bulain.hibernate.entity.Vehicle implements java.io.Serializable {


     /**
     * 
     */
    private static final long serialVersionUID = 9177699090043505844L;
    private String bikeInfo;

    public Bike() {
    }

    public Bike(String name, String bikeInfo) {
        super(name);        
       this.bikeInfo = bikeInfo;
    }
   
    public String getBikeInfo() {
        return this.bikeInfo;
    }
    
    public void setBikeInfo(String bikeInfo) {
        this.bikeInfo = bikeInfo;
    }




}


