package com.bulain.hibernate.entity;
// Generated 2011-10-25 20:06:48 by Hibernate Tools 3.2.2.GA



/**
 * Car generated by hbm2java
 */
public class Car extends com.bulain.hibernate.entity.Vehicle implements java.io.Serializable {


     /**
     * 
     */
    private static final long serialVersionUID = 5257761992704016475L;
    private String carInfo;

    public Car() {
    }

    public Car(String name, String carInfo) {
        super(name);        
       this.carInfo = carInfo;
    }
   
    public String getCarInfo() {
        return this.carInfo;
    }
    
    public void setCarInfo(String carInfo) {
        this.carInfo = carInfo;
    }




}


