package com.bulain.hibernate.entity;
// Generated 2011-10-25 20:52:55 by Hibernate Tools 3.2.2.GA



/**
 * CellPhone generated by hbm2java
 */
public class CellPhone extends com.bulain.hibernate.entity.Phone implements java.io.Serializable {


     /**
     * 
     */
    private static final long serialVersionUID = -3477157533443043168L;
    private String cellInfo;

    public CellPhone() {
    }

    public CellPhone(String name, String cellInfo) {
        super(name);        
       this.cellInfo = cellInfo;
    }
   
    public String getCellInfo() {
        return this.cellInfo;
    }
    
    public void setCellInfo(String cellInfo) {
        this.cellInfo = cellInfo;
    }




}


