package com.bulain.hibernate.entity;
// Generated 2011-10-25 20:35:54 by Hibernate Tools 3.2.2.GA



/**
 * Computer generated by hbm2java
 */
public class Computer  implements java.io.Serializable {


     /**
     * 
     */
    private static final long serialVersionUID = 722630091196925609L;
    private long id;
     private String name;

    public Computer() {
    }

    public Computer(String name) {
       this.name = name;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


