package com.bulain.hibernate.entity;
// Generated 2011-10-22 19:50:42 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import com.bulain.common.model.Entity;
import com.bulain.common.model.Trackable;

/**
 * GroupUser generated by hbm2java
 */
public class GroupUser implements Entity, Trackable, java.io.Serializable {


     /**
     * 
     */
    private static final long serialVersionUID = -2350394695078154909L;
    private Long id;
     private User user;
     private Group group;
     private String createdBy;
     private Date createdAt;
     private String updatedBy;
     private Date updatedAt;

    public GroupUser() {
    }

    public GroupUser(User user, Group group, String createdBy, Date createdAt, String updatedBy, Date updatedAt) {
       this.user = user;
       this.group = group;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.updatedBy = updatedBy;
       this.updatedAt = updatedAt;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


