package com.bulain.hibernate.entity;
// Generated 2011-10-25 20:15:48 by Hibernate Tools 3.2.2.GA



/**
 * Pear generated by hbm2java
 */
public class Pear extends com.bulain.hibernate.entity.Fruit implements java.io.Serializable {


     /**
     * 
     */
    private static final long serialVersionUID = -5798235555158171544L;
    private String pearInfo;

    public Pear() {
    }

    public Pear(String name, String pearInfo) {
        super(name);        
       this.pearInfo = pearInfo;
    }
   
    public String getPearInfo() {
        return this.pearInfo;
    }
    
    public void setPearInfo(String pearInfo) {
        this.pearInfo = pearInfo;
    }




}


