package com.bulain.hibernate.entity;
// Generated 2011-10-25 20:52:55 by Hibernate Tools 3.2.2.GA



/**
 * Phone generated by hbm2java
 */
public class Phone  implements java.io.Serializable {


     /**
     * 
     */
    private static final long serialVersionUID = 6901534127750466306L;
    private long id;
     private String name;

    public Phone() {
    }

    public Phone(String name) {
       this.name = name;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


