package com.bulain.hibernate.entity;
// Generated 2011-10-25 20:52:55 by Hibernate Tools 3.2.2.GA



/**
 * TelPhone generated by hbm2java
 */
public class TelPhone extends com.bulain.hibernate.entity.Phone implements java.io.Serializable {


     /**
     * 
     */
    private static final long serialVersionUID = 289588948449253070L;
    private String telInfo;

    public TelPhone() {
    }

    public TelPhone(String name, String telInfo) {
        super(name);        
       this.telInfo = telInfo;
    }
   
    public String getTelInfo() {
        return this.telInfo;
    }
    
    public void setTelInfo(String telInfo) {
        this.telInfo = telInfo;
    }




}


