package com.bulain.hibernate.entity;
// Generated 2011-10-25 20:06:48 by Hibernate Tools 3.2.2.GA



/**
 * Vehicle generated by hbm2java
 */
public class Vehicle  implements java.io.Serializable {


     /**
     * 
     */
    private static final long serialVersionUID = 415770644107456953L;
    private Long id;
     private String name;

    public Vehicle() {
    }

    public Vehicle(String name) {
       this.name = name;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


